### ISSUE TITLE
Does not work with Proxies

### ISSUE THREAD

**Issue by hamnis** [sonatype/sisu-xmlrpc#2]
I need this component to work with HTTP proxies.

**Comment by jfarcand** [comment]
Salut, I will take a look. Do you know if that feature ever worked? I suspect it has never been implemented.

**Comment by hamnis** [comment]
I'm not sure. but there are two JVM system properties that might be useful to apply if they appear: Those are called "http.proxyHost" and "http.proxyPort".

http://download.oracle.com/javase/1.4.2/docs/guide/net/properties.html

**Comment by jfarcand** [comment]
Fixed

https://github.com/sonatype/sisu-xmlrpc/commit/ea9ccc751a65763a53f8ad6c1119fbea7850a7a1
